apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouseserver
spec:
  selector:
    matchLabels:
      app: warehouseserver
  template:
    metadata:
      labels:
        app: warehouseserver
    spec:
      containers:
      - image: deni1688/warehouseserver:latest
        name: warehouseserver
        resources: {}
        imagePullPolicy: Always
        env:
          # rabbitmq
          - name: MQ_USER
            value: guest
          - name: MQ_PASS
            value: guest
          - name: MQ_ADDR
            valueFrom:
              configMapKeyRef:
                key: rabbitmq-uri
                name: kubestore-config
          # postgres
          - name: DB_ADDR
            valueFrom:
              configMapKeyRef:
                key: postgrestore-uri
                name: kubestore-config
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: postgres-db-user
                name: db-secrets
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: postgres-db-pass
                name: db-secrets
      restartPolicy: Always
