version: "3.9"

services:
  productclient:
    build: ./ui
    ports:
      - "8877:80"
    networks:
      - "kubestore_net"

  adminserver:
    build: ./admin
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      RABBIT_MQ_URI: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - "kubestore_net"

  catalogserver:
    build: ./catalog
    restart: unless-stopped
    environment:
      RABBIT_MQ_URI: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - "kubestore_net"

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - "kubestore_net"

networks:
  kubestore_net:
    driver: "bridge"


