apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogserver
spec:
  selector:
    matchLabels:
      app: catalogserver
  template:
    metadata:
      labels:
        app: catalogserver
    spec:
      containers:
      - image: deni1688/catalogserver:latest
        name: catalogserver
        resources: {}
        imagePullPolicy: Always
        env:
          # rabbitmq
          - name: MQ_USER
            value: guest
          - name: MQ_PASS
            value: guest
          - name: MQ_ADDR
            valueFrom:
              configMapKeyRef:
                key: rabbitmq-uri
                name: kubestore-config
          # mongo
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: mongo-db-user
                name: db-secrets
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: mongo-db-pass
                name: db-secrets
          - name: DB_ADDR
            valueFrom:
              configMapKeyRef:
                key: mongostore-uri
                name: kubestore-config
      restartPolicy: Always
