apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongostore
  labels:
    app: mongostore
spec:
  replicas: 1
  template:
    metadata:
      name: mongostore
      labels:
        app: mongostore
    spec:
      containers:
        - name: mongostore
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo-db-user
                  name: db-secrets
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-db-pass
                  name: db-secrets
      restartPolicy: Always
  selector:
    matchLabels:
      app: mongostore

---

apiVersion: v1
kind: Service
metadata:
  name: mongostore-service
spec:
  selector:
    app: mongostore
  ports:
    - port: 27017
