spring:
  rabbitmq:
    username: "${MQ_USER}"
    password: "${MQ_PASS}"
    host: "${MQ_ADDR}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
  datasource:
    url: "jdbc:postgresql://${DB_ADDR}/stocks"
    username: "${DB_USER}"
    password: "${DB_PASS}"
